@startuml ER

package Project {
   entity T_Users {
      + **id**: int <<PK>>
      ---
      * **name**: varchar(255) nullable
      * **state_description**: varchar(255) nullable
      * **last_logined_at**: datetime nullable
      * **created_at**: datetime nullable
   }

   entity M_Config {
      + **id**: int <<PK>>
      ---
      * **name**: varchar(255) <<UK>>
      * **value_set**: json
      * **description**: varchar(255) nullable
   }

   entity T_UserConfigValues {
      # **user_id**: int <<FK>>
      # **config_id**: int <<FK>>
      ---
      * **value**: varchar(255)
   }
}


T_Users ||--o{ T_UserConfigValues
T_UserConfigValues }o--|| M_Config

@enduml